### ISSUE TITLE
Fix bug: the VM takes >5 seconds for each `sudo` command

### ISSUE THREAD

**Issue by fzyzcjy** [mit-pdos/secfs-skeleton#3]
This can be solved by adding the following lines to the `/etc/hosts` file:

```
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4 6858-v20
::1 localhost localhost.localdomain localhost6 localhost6.localdomain6 6858-v20
```

The critical part is to let `6858-v20` to be pointed to localhost. The actual cause is that, the hostname of this VM is modified to `6858-v20`, but the `/etc/hosts` has not been modified.

**Comment by zeldovich** [comment]
Thank you!  I've updated the VM build script so this should be fixed when we re-generate the VM image for the next semester we're teaching 6.858.

**Comment by fzyzcjy** [comment]
@zeldovich You are welcome!
